/** Seed content pulled from johnandsheilaludgate.com and Apple Music. */

export type SeedAlbum = {
  title: string;
  year: number;
  slug: string;
  cover: string;
  appleUrl: string;
  blurb: string;
  kind: "studio" | "live";
  creditsPdf?: string;
  lyricsPdf?: string;
  tracks: { n: number; title: string; duration: string }[];
};

export type SeedShow = {
  date: string;
  time: string;
  venue: string;
  address: string;
  city: string;
  province: string;
};

export const SEED_ALBUMS: SeedAlbum[] = [
  {
    title: "Folk Rock",
    year: 2025,
    slug: "folk-rock",
    cover: "/media/albums/folk-rock.jpg",
    appleUrl: "https://music.apple.com/us/album/folk-rock/1852258611",
    blurb: "John and Sheila are joined by their sons Luke, Anthony and Shane. The folk of the duo meets the rock of Beautiful Nothing \u2014 acoustic songs with a new electric twist. Released November 2025.",
    kind: "studio",
    creditsPdf: "/media/credits/folk-rock.pdf",
    tracks: [
      { n: 1, title: "Electric Guitars", duration: "4:19" },
      { n: 2, title: "Northern Soul", duration: "4:06" },
      { n: 3, title: "Masquerade", duration: "3:29" },
      { n: 4, title: "Sad & Beautiful", duration: "5:57" },
      { n: 5, title: "Never Too Late", duration: "4:17" },
      { n: 6, title: "Coming Home To You", duration: "2:59" },
      { n: 7, title: "Fleeing Forward", duration: "3:33" },
      { n: 8, title: "Requiem For Love", duration: "4:35" },
      { n: 9, title: "Grace", duration: "3:46" },
      { n: 10, title: "Through The Glass Darkly", duration: "3:23" },
      { n: 11, title: "One Thing's For Certain", duration: "3:25" },
      { n: 12, title: "I Walk On", duration: "7:44" },
    ],
  },
  {
    title: "The Kitchen Sessions",
    year: 2023,
    slug: "the-kitchen-sessions",
    cover: "/media/albums/the-kitchen-sessions.jpg",
    appleUrl: "https://music.apple.com/us/album/the-kitchen-sessions/1691140812",
    blurb: "Recorded around the family kitchen table in 2023. #2 in downloads on the APD Global Radio Indicator Chart (June 2023). \u201cThe Gift Of An Ordinary Day\u201d made the Folk Alliance International Top 10.",
    kind: "studio",
    creditsPdf: "/media/credits/kitchen-sessions.pdf",
    lyricsPdf: "/media/lyrics/kitchen-sessions.pdf",
    tracks: [
      { n: 1, title: "The Gift Of An Ordinary Day", duration: "3:02" },
      { n: 2, title: "Long Shadows", duration: "3:35" },
      { n: 3, title: "A Silent Prayer", duration: "3:38" },
      { n: 4, title: "Wayfaring Stranger", duration: "4:09" },
      { n: 5, title: "Time Can't Stand Still", duration: "3:44" },
      { n: 6, title: "Nineteen Eighty-Four All Over Again", duration: "4:12" },
      { n: 7, title: "Daily Dose Of Nightly News", duration: "3:17" },
      { n: 8, title: "On Valentine's Day", duration: "3:26" },
      { n: 9, title: "Children Having Children", duration: "4:08" },
      { n: 10, title: "Halloween Dad", duration: "4:01" },
      { n: 11, title: "Songs Of Peace And Love", duration: "3:55" },
      { n: 12, title: "End Of Summer", duration: "3:32" },
    ],
  },
  {
    title: "What the Camera Couldn't See",
    year: 2018,
    slug: "what-the-camera-couldn-t-see",
    cover: "/media/albums/what-the-camera-couldn-t-see.jpg",
    appleUrl: "https://music.apple.com/us/album/what-the-camera-couldnt-see/1692032240",
    blurb: "2018 studio album. Jim Marino of CFMU\u2019s Freewheeling Folk Show named it one of his Top 10 CDs of the year for Penguin Eggs Magazine.",
    kind: "studio",
    creditsPdf: "/media/credits/what-the-camera.pdf",
    lyricsPdf: "/media/lyrics/what-the-camera.pdf",
    tracks: [
      { n: 1, title: "Through The Glass Darkly", duration: "3:23" },
      { n: 2, title: "The Old Man Knows", duration: "3:22" },
      { n: 3, title: "Sad & Beautiful", duration: "5:57" },
      { n: 4, title: "Between A Whisper & A Sigh", duration: "3:16" },
      { n: 5, title: "Trick Of The Light", duration: "3:13" },
      { n: 6, title: "Back In The Shadows", duration: "3:53" },
      { n: 7, title: "Hush Little Baby", duration: "3:18" },
      { n: 8, title: "I Pray", duration: "3:52" },
      { n: 9, title: "Employee 41759", duration: "3:52" },
      { n: 10, title: "I Walk On", duration: "7:44" },
      { n: 11, title: "Almost Through", duration: "3:25" },
    ],
  },
  {
    title: "Two, Three, Four... (Live - Volume Two)",
    year: 2019,
    slug: "two-three-four-live-volume-two",
    cover: "/media/albums/two-three-four-live-volume-two.jpg",
    appleUrl: "https://music.apple.com/us/album/two-three-four-live-volume-two/1821934218",
    blurb: "Live off-the-floor, 2019. Just two voices, an acoustic guitar, a bass and a harmonica \u2014 the count-in that starts almost every Ludgate show.",
    kind: "live",
    creditsPdf: "/media/credits/two-three-four-vol-two.pdf",
    tracks: [
      { n: 1, title: "On This Guitar (Live)", duration: "2:09" },
      { n: 2, title: "Time Can't Stand Still (Live)", duration: "3:44" },
      { n: 3, title: "Trick Of The Light (Live)", duration: "3:12" },
      { n: 4, title: "Between A Whisper And A Sigh (Live)", duration: "4:47" },
      { n: 5, title: "Long Shadows (Live)", duration: "3:44" },
      { n: 6, title: "Employee 41759 (Live)", duration: "4:16" },
      { n: 7, title: "End of Summer (Live)", duration: "3:58" },
      { n: 8, title: "Riding On This Train Again (Live)", duration: "3:21" },
      { n: 9, title: "Songs Of Peace And Love (Live)", duration: "4:05" },
    ],
  },
  {
    title: "Two, Three, Four... (Live - Volume One)",
    year: 2014,
    slug: "two-three-four-live-volume-one",
    cover: "/media/albums/two-three-four-live-volume-one.jpg",
    appleUrl: "https://music.apple.com/us/album/two-three-four-live-volume-one/1821933520",
    blurb: "Live off-the-floor, 2014. Stripped-down performances of old and new songs that capture the character of a John & Sheila night.",
    kind: "live",
    creditsPdf: "/media/credits/two-three-four-vol-one.pdf",
    tracks: [
      { n: 1, title: "Robert Frost Said (Live)", duration: "3:25" },
      { n: 2, title: "Masquerade (Live)", duration: "3:17" },
      { n: 3, title: "Family Man (Live)", duration: "3:33" },
      { n: 4, title: "Between Us (Live)", duration: "3:06" },
      { n: 5, title: "Sad & Beautiful (Live)", duration: "4:54" },
      { n: 6, title: "About Me (Live)", duration: "4:56" },
      { n: 7, title: "Hockey Night In Canada (Live)", duration: "4:04" },
      { n: 8, title: "The Innocent Years (Live)", duration: "4:36" },
      { n: 9, title: "Bobblehead Boogie (The Yes Man Song) [Live]", duration: "3:15" },
      { n: 10, title: "A Candle For The Prodigal (Live)", duration: "3:56" },
      { n: 11, title: "Steinbeck's Guitar (Live)", duration: "3:31" },
      { n: 12, title: "Coureur de Bois To Coureur d'\u00c9toiles (Live)", duration: "4:26" },
      { n: 13, title: "Walk On (Live)", duration: "5:22" },
      { n: 14, title: "One Thing's For Certain (Live)", duration: "3:41" },
      { n: 15, title: "Wedding Song (Live)", duration: "4:14" },
      { n: 16, title: "I'm A Dog (Live)", duration: "2:58" },
      { n: 17, title: "A Dog's Last Ride (Live)", duration: "4:27" },
      { n: 18, title: "Northern Soul (Live)", duration: "4:51" },
      { n: 19, title: "Too Much Body (Live)", duration: "3:24" },
      { n: 20, title: "I'm Not Worried (Live)", duration: "2:56" },
    ],
  },
  {
    title: "Northern Soul",
    year: 2013,
    slug: "northern-soul",
    cover: "/media/albums/northern-soul.jpg",
    appleUrl: "https://music.apple.com/us/album/northern-soul/1687219124",
    blurb: "2013. The title track won Folk Music Ontario\u2019s Songs From The Heart (Multicultural). Three songs were recognized by NSAI in Nashville.",
    kind: "studio",
    creditsPdf: "/media/credits/northern-soul.pdf",
    lyricsPdf: "/media/lyrics/northern-soul.pdf",
    tracks: [
      { n: 1, title: "Electric Guitars", duration: "4:19" },
      { n: 2, title: "Northern Soul", duration: "4:06" },
      { n: 3, title: "One Thing\u2019s for Certain", duration: "3:25" },
      { n: 4, title: "In Between Days", duration: "3:48" },
      { n: 5, title: "Coming Home to You", duration: "2:59" },
      { n: 6, title: "Blink", duration: "3:25" },
      { n: 7, title: "Requiem for Love", duration: "4:35" },
      { n: 8, title: "Fine Line", duration: "3:20" },
      { n: 9, title: "Inside Job", duration: "3:10" },
      { n: 10, title: "Let\u2019s Just Say", duration: "4:36" },
      { n: 11, title: "A Candle for the Prodigal", duration: "3:33" },
      { n: 12, title: "I\u2019m a Dog", duration: "2:29" },
      { n: 13, title: "A Dog\u2019s Last Ride (For Abbie)", duration: "3:54" },
    ],
  },
  {
    title: "Running Through The Innocent Years",
    year: 2011,
    slug: "running-through-the-innocent-years",
    cover: "/media/albums/running-through-the-innocent-years.jpg",
    appleUrl: "https://music.apple.com/us/album/running-through-the-innocent-years/1692031894",
    blurb: "2011. Strong folk/roots airplay in Canada and the U.S. The video for \u201cNever Too Late\u201d was shot in and around Hamilton.",
    kind: "studio",
    creditsPdf: "/media/credits/innocent-years.pdf",
    lyricsPdf: "/media/lyrics/innocent-years.pdf",
    tracks: [
      { n: 1, title: "Payback Road", duration: "4:12" },
      { n: 2, title: "Never Too Late", duration: "4:17" },
      { n: 3, title: "Masquerade", duration: "3:29" },
      { n: 4, title: "The Innocent Years", duration: "4:05" },
      { n: 5, title: "Time\u2019s March", duration: "4:15" },
      { n: 6, title: "Get It All In", duration: "3:09" },
      { n: 7, title: "Fly Away", duration: "3:14" },
      { n: 8, title: "The Coming of Winter", duration: "3:46" },
      { n: 9, title: "Sealed With A Song", duration: "3:14" },
      { n: 10, title: "Colours", duration: "3:33" },
      { n: 11, title: "Wasted Time", duration: "2:46" },
    ],
  },
  {
    title: "Suburban Folk",
    year: 2009,
    slug: "suburban-folk",
    cover: "/media/albums/suburban-folk.jpg",
    appleUrl: "https://music.apple.com/us/album/suburban-folk/1692032037",
    blurb: "Released in 2009 as Suburban Tales / Suburban Folk. The video for \u201cSteinbeck\u2019s Guitar\u201d was picked up by the Steinbeck Centre in Salinas, California.",
    kind: "studio",
    creditsPdf: "/media/credits/suburban-tales.pdf",
    tracks: [
      { n: 1, title: "Grace", duration: "3:46" },
      { n: 2, title: "Karaoke Land", duration: "3:11" },
      { n: 3, title: "For You", duration: "3:15" },
      { n: 4, title: "Fleeing Forward", duration: "3:34" },
      { n: 5, title: "Bobblehead Boogie - The Yes Man Song", duration: "2:22" },
      { n: 6, title: "Steinbeck's Guitar", duration: "3:16" },
      { n: 7, title: "The Garden", duration: "2:25" },
      { n: 8, title: "Adam's Blues", duration: "2:51" },
      { n: 9, title: "Robert Frost Said", duration: "3:35" },
      { n: 10, title: "Another Mile", duration: "2:32" },
      { n: 11, title: "Forgotten", duration: "3:19" },
      { n: 12, title: "Trickle Down", duration: "2:38" },
      { n: 13, title: "Recovered", duration: "4:23" },
      { n: 14, title: "Walls Go Up", duration: "3:00" },
      { n: 15, title: "I'm Not Worried", duration: "2:24" },
    ],
  },
  {
    title: "Passengers",
    year: 2003,
    slug: "passengers",
    cover: "/media/albums/passengers.jpg",
    appleUrl: "https://music.apple.com/us/album/passengers/1692029571",
    blurb: "The first studio CD. Nominated at the Hamilton Music Scene awards.",
    kind: "studio",
    creditsPdf: "/media/credits/passengers.pdf",
    tracks: [
      { n: 1, title: "The Lighthouse", duration: "2:32" },
      { n: 2, title: "Let Me Be Yours", duration: "2:31" },
      { n: 3, title: "Armour Of God", duration: "1:56" },
      { n: 4, title: "As A Father", duration: "3:00" },
      { n: 5, title: "The Answering Heart", duration: "3:14" },
      { n: 6, title: "Between You and I", duration: "2:46" },
      { n: 7, title: "Jesus Lover Of My Soul", duration: "3:22" },
      { n: 8, title: "Rest My Soul", duration: "3:03" },
      { n: 9, title: "A Seekers Prayer", duration: "3:18" },
      { n: 10, title: "Give Me Eyes To See", duration: "3:22" },
      { n: 11, title: "Lord We Need Your Touch", duration: "3:24" },
      { n: 12, title: "Backslider's Lament", duration: "4:52" },
      { n: 13, title: "In The Still Of The Night", duration: "3:15" },
      { n: 14, title: "Benediction", duration: "1:15" },
    ],
  },
];

export const SEED_SHOWS: SeedShow[] = [
  { date: "2026-12-03", time: "15:00", venue: "The Kensington", address: "25 Lakeshore Rd W", city: "Oakville", province: "ON" },
  { date: "2026-11-19", time: "14:00", venue: "Appleby Place", address: "500 Appleby Line", city: "Burlington", province: "ON" },
  { date: "2026-11-13", time: "14:30", venue: "Birkdale Place", address: "611 Farmstead Dr", city: "Milton", province: "ON" },
  { date: "2026-11-12", time: "14:45", venue: "Christopher Terrace", address: "3131 New St", city: "Burlington", province: "ON" },
  { date: "2026-11-05", time: "14:15", venue: "The Beechwood", address: "1500 Rathburn Rd E", city: "Mississauga", province: "ON" },
  { date: "2026-10-30", time: "14:30", venue: "Lundy Manor", address: "7860 Lundy's Ln", city: "Niagara Falls", province: "ON" },
  { date: "2026-10-24", time: "14:00", venue: "The Village Of Wentworth Heights", address: "1620 Upper Wentworth St", city: "Hamilton", province: "ON" },
  { date: "2026-10-15", time: "14:15", venue: "The Beechwood", address: "1500 Rathburn Rd E", city: "Mississauga", province: "ON" },
  { date: "2026-10-13", time: "19:15", venue: "The Village Of Tansley Woods", address: "4100 Upper Middle Rd", city: "Burlington", province: "ON" },
  { date: "2026-10-08", time: "15:00", venue: "Churchill Place", address: "345 Church St", city: "Oakville", province: "ON" },
  { date: "2026-09-10", time: "15:00", venue: "The Kensington", address: "25 Lakeshore Rd W", city: "Oakville", province: "ON" },
  { date: "2026-09-08", time: "14:00", venue: "The Village Of Riverside Glen", address: "60 Woodlawn Rd E", city: "Guelph", province: "ON" },
  { date: "2026-08-28", time: "14:30", venue: "Park View", address: "254 Dalhousie St", city: "Brantford", province: "ON" },
  { date: "2026-08-09", time: "13:45", venue: "The Court At Rushdale", address: "1360 Upper Sherman Ave", city: "Hamilton", province: "ON" },
  { date: "2026-08-06", time: "14:15", venue: "The Beechwood", address: "1500 Rathburn Rd E", city: "Mississauga", province: "ON" },
  { date: "2026-07-31", time: "14:00", venue: "Appleby Place", address: "500 Appleby Line", city: "Burlington", province: "ON" },
  { date: "2026-07-16", time: "14:15", venue: "The Beechwood", address: "1500 Rathburn Rd E", city: "Mississauga", province: "ON" },
  { date: "2026-07-09", time: "14:45", venue: "Christopher Terrace", address: "3131 New St", city: "Burlington", province: "ON" },
  { date: "2026-07-08", time: "15:00", venue: "Churchill Place", address: "345 Church St", city: "Oakville", province: "ON" },
  { date: "2026-07-01", time: "14:00", venue: "Burlington Gardens", address: "300 Plains Rd W", city: "Burlington", province: "ON" },
  { date: "2026-06-30", time: "14:15", venue: "Hampton Terrace", address: "75 Plains Road West", city: "Burlington", province: "ON" },
  { date: "2026-05-28", time: "15:00", venue: "The Kensington", address: "25 Lakeshore Rd W", city: "Oakville", province: "ON" },
  { date: "2026-05-22", time: "14:30", venue: "Birkdale Place", address: "611 Farmstead Dr", city: "Milton", province: "ON" },
  { date: "2026-05-13", time: "14:30", venue: "Lundy Manor", address: "7860 Lundy's Ln", city: "Niagara Falls", province: "ON" },
  { date: "2026-05-12", time: "19:15", venue: "The Village Of Tansley Woods", address: "4100 Upper Middle Rd", city: "Burlington", province: "ON" },
  { date: "2026-05-09", time: "14:00", venue: "The Village Of Wentworth Heights", address: "1620 Upper Wentworth St", city: "Hamilton", province: "ON" },
  { date: "2026-05-07", time: "14:15", venue: "The Beechwood", address: "1500 Rathburn Rd E", city: "Mississauga", province: "ON" },
  { date: "2026-04-16", time: "14:15", venue: "The Village Of Riverside Glen", address: "60 Woodlawn Rd E", city: "Guelph", province: "ON" },
  { date: "2026-04-12", time: "13:45", venue: "The Court At Rushdale", address: "1360 Upper Sherman Ave", city: "Hamilton", province: "ON" },
  { date: "2026-04-09", time: "14:15", venue: "The Beechwood", address: "1500 Rathburn Rd E", city: "Mississauga", province: "ON" },
  { date: "2026-04-08", time: "14:15", venue: "Hampton Terrace", address: "75 Plains Road West", city: "Burlington", province: "ON" },
  { date: "2026-03-27", time: "14:30", venue: "Park View", address: "254 Dalhousie St, Brantford, ON N3S 3V2", city: "Brantford", province: "ON" },
  { date: "2026-03-25", time: "14:00", venue: "SLEC Suite", address: "120, 2030 Bristol Cir", city: "Oakville", province: "ON" },
  { date: "2026-03-17", time: "14:30", venue: "Birkdale Place", address: "611 Farmstead Dr", city: "Milton", province: "ON" },
  { date: "2026-02-25", time: "14:00", venue: "St. Joseph's Villa", address: "56 Governors Rd", city: "Dundas", province: "ON" },
  { date: "2026-02-19", time: "14:45", venue: "Christopher Terrace", address: "3131 New St", city: "Burlington", province: "ON" },
  { date: "2026-02-13", time: "14:15", venue: "Hampton Terrace", address: "75 Plains Road West", city: "Burlington", province: "ON" },
  { date: "2026-02-11", time: "15:00", venue: "St. Joseph's Villa", address: "56 Governors Rd", city: "Dundas", province: "ON" },
  { date: "2026-02-05", time: "15:00", venue: "The Kensington", address: "25 Lakeshore Rd W", city: "Oakville", province: "ON" },
  { date: "2026-01-27", time: "19:00", venue: "Shalom Village", address: "70 Macklin St N", city: "Hamilton", province: "ON" },
  { date: "2026-01-20", time: "19:15", venue: "The Village Of Tansley Woods", address: "4100 Upper Middle Rd", city: "Burlington", province: "ON" },
  { date: "2026-01-15", time: "14:00", venue: "Appleby Place", address: "500 Appleby Line", city: "Burlington", province: "ON" },
  { date: "2026-01-08", time: "14:15", venue: "The Beechwood", address: "1500 Rathburn Rd E", city: "Mississauga", province: "ON" },
];
